# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 460))
        MainWindow.setMaximumSize(QtCore.QSize(900, 460))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(80, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(280, 290, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(180, 290, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 330, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(580, 370, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 330, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.Pclass_box = QtWidgets.QComboBox(self.centralwidget)
        self.Pclass_box.setGeometry(QtCore.QRect(110, 110, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Pclass_box.setFont(font)
        self.Pclass_box.setObjectName("Pclass_box")
        self.Pclass_box.addItem("")
        self.Pclass_box.addItem("")
        self.Pclass_box.addItem("")
        self.gender_box = QtWidgets.QComboBox(self.centralwidget)
        self.gender_box.setGeometry(QtCore.QRect(110, 150, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.gender_box.setFont(font)
        self.gender_box.setObjectName("gender_box")
        self.gender_box.addItem("")
        self.gender_box.addItem("")
        self.Fare_box = QtWidgets.QComboBox(self.centralwidget)
        self.Fare_box.setGeometry(QtCore.QRect(110, 230, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Fare_box.setFont(font)
        self.Fare_box.setObjectName("Fare_box")
        self.Fare_box.addItem("")
        self.Fare_box.addItem("")
        self.Fare_box.addItem("")
        self.Fare_box.addItem("")
        self.Pclass = QtWidgets.QLabel(self.centralwidget)
        self.Pclass.setGeometry(QtCore.QRect(30, 110, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.Pclass.setFont(font)
        self.Pclass.setObjectName("Pclass")
        self.Sex = QtWidgets.QLabel(self.centralwidget)
        self.Sex.setGeometry(QtCore.QRect(30, 150, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.Sex.setFont(font)
        self.Sex.setObjectName("Sex")
        self.Age = QtWidgets.QLabel(self.centralwidget)
        self.Age.setGeometry(QtCore.QRect(30, 190, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.Age.setFont(font)
        self.Age.setObjectName("Age")
        self.Fare = QtWidgets.QLabel(self.centralwidget)
        self.Fare.setGeometry(QtCore.QRect(30, 230, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.Fare.setFont(font)
        self.Fare.setObjectName("Fare")
        self.FamilySize = QtWidgets.QLabel(self.centralwidget)
        self.FamilySize.setGeometry(QtCore.QRect(219, 230, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.FamilySize.setFont(font)
        self.FamilySize.setObjectName("FamilySize")
        self.Embarked_box = QtWidgets.QComboBox(self.centralwidget)
        self.Embarked_box.setGeometry(QtCore.QRect(330, 150, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Embarked_box.setFont(font)
        self.Embarked_box.setObjectName("Embarked_box")
        self.Embarked_box.addItem("")
        self.Embarked_box.addItem("")
        self.Embarked_box.addItem("")
        self.Title_box = QtWidgets.QComboBox(self.centralwidget)
        self.Title_box.setGeometry(QtCore.QRect(330, 190, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Title_box.setFont(font)
        self.Title_box.setObjectName("Title_box")
        self.Title_box.addItem("")
        self.Title_box.addItem("")
        self.Title_box.addItem("")
        self.Cabin = QtWidgets.QLabel(self.centralwidget)
        self.Cabin.setGeometry(QtCore.QRect(219, 110, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.Cabin.setFont(font)
        self.Cabin.setObjectName("Cabin")
        self.Embarked = QtWidgets.QLabel(self.centralwidget)
        self.Embarked.setGeometry(QtCore.QRect(219, 150, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.Embarked.setFont(font)
        self.Embarked.setObjectName("Embarked")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(219, 190, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.Cabin_box = QtWidgets.QComboBox(self.centralwidget)
        self.Cabin_box.setGeometry(QtCore.QRect(330, 110, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.Cabin_box.setFont(font)
        self.Cabin_box.setObjectName("Cabin_box")
        self.Cabin_box.addItem("")
        self.Cabin_box.addItem("")
        self.Cabin_box.addItem("")
        self.Cabin_box.addItem("")
        self.Cabin_box.addItem("")
        self.Cabin_box.addItem("")
        self.Cabin_box.addItem("")
        self.Cabin_box.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(179, 30, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(460, 39, 400, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.result.sizePolicy().hasHeightForWidth())
        self.result.setSizePolicy(sizePolicy)
        self.result.setMinimumSize(QtCore.QSize(400, 300))
        self.result.setText("")
        self.result.setObjectName("result")
        self.AgeBox = QtWidgets.QSpinBox(self.centralwidget)
        self.AgeBox.setGeometry(QtCore.QRect(110, 190, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.AgeBox.sizePolicy().hasHeightForWidth())
        self.AgeBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.AgeBox.setFont(font)
        self.AgeBox.setMinimum(1)
        self.AgeBox.setObjectName("AgeBox")
        self.familySizeBox = QtWidgets.QSpinBox(self.centralwidget)
        self.familySizeBox.setGeometry(QtCore.QRect(330, 230, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(self.familySizeBox.sizePolicy().hasHeightForWidth())
        self.familySizeBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.familySizeBox.setFont(font)
        self.familySizeBox.setMinimum(1)
        self.familySizeBox.setMaximum(11)
        self.familySizeBox.setObjectName("familySizeBox")
        self.label_score = QtWidgets.QLabel(self.centralwidget)
        self.label_score.setGeometry(QtCore.QRect(180, 390, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_score.setFont(font)
        self.label_score.setText("")
        self.label_score.setObjectName("label_score")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 390, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "SVM"))
        self.radioButton_2.setText(_translate("MainWindow", "RF"))
        self.radioButton_3.setText(_translate("MainWindow", "DNN"))
        self.pushButton.setText(_translate("MainWindow", "Train"))
        self.label.setText(_translate("MainWindow", "Result"))
        self.pushButton_3.setText(_translate("MainWindow", "Predict"))
        self.Pclass_box.setItemText(0, _translate("MainWindow", "1"))
        self.Pclass_box.setItemText(1, _translate("MainWindow", "2"))
        self.Pclass_box.setItemText(2, _translate("MainWindow", "3"))
        self.gender_box.setItemText(0, _translate("MainWindow", "Male"))
        self.gender_box.setItemText(1, _translate("MainWindow", "Female"))
        self.Fare_box.setItemText(0, _translate("MainWindow", "high"))
        self.Fare_box.setItemText(1, _translate("MainWindow", "medium"))
        self.Fare_box.setItemText(2, _translate("MainWindow", "low"))
        self.Fare_box.setItemText(3, _translate("MainWindow", "beggar"))
        self.Pclass.setText(_translate("MainWindow", "Pclass"))
        self.Sex.setText(_translate("MainWindow", "Sex"))
        self.Age.setText(_translate("MainWindow", "Age"))
        self.Fare.setText(_translate("MainWindow", "Fare"))
        self.FamilySize.setText(_translate("MainWindow", "Family Size"))
        self.Embarked_box.setItemText(0, _translate("MainWindow", "0"))
        self.Embarked_box.setItemText(1, _translate("MainWindow", "1"))
        self.Embarked_box.setItemText(2, _translate("MainWindow", "2"))
        self.Title_box.setItemText(0, _translate("MainWindow", "Mr"))
        self.Title_box.setItemText(1, _translate("MainWindow", "Miss"))
        self.Title_box.setItemText(2, _translate("MainWindow", "Mrs"))
        self.Cabin.setText(_translate("MainWindow", "Cabin"))
        self.Embarked.setText(_translate("MainWindow", "Embarked"))
        self.Title.setText(_translate("MainWindow", "Title"))
        self.Cabin_box.setItemText(0, _translate("MainWindow", "A"))
        self.Cabin_box.setItemText(1, _translate("MainWindow", "B"))
        self.Cabin_box.setItemText(2, _translate("MainWindow", "C"))
        self.Cabin_box.setItemText(3, _translate("MainWindow", "D"))
        self.Cabin_box.setItemText(4, _translate("MainWindow", "E"))
        self.Cabin_box.setItemText(5, _translate("MainWindow", "F"))
        self.Cabin_box.setItemText(6, _translate("MainWindow", "G"))
        self.Cabin_box.setItemText(7, _translate("MainWindow", "T"))
        self.label_2.setText(_translate("MainWindow", "Name :"))
        self.label_4.setText(_translate("MainWindow", "Score :"))

